<?php

namespace AppBundle\Doctrine\Repository;

use AppBundle\Entity\Bid;

/**
 * BidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BidRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Bid $bid
     */
    public function create(Bid $bid)
    {
        $date = new \DateTime();
        $bid->setCreated($date);

        $this->_em->persist($bid);
        $this->_em->flush();
        $this->_em->clear();
    }
}
