<?php

namespace AppBundle\Doctrine\Repository;

use AppBundle\Entity\Comment;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function create(Comment $item)
    {
        $date = new \DateTime();
        $item->setCreated($date);

        $this->_em->persist($item);
        $this->_em->flush();
        $this->_em->clear();
    }
}
