<?php

namespace AppBundle\Doctrine\Repository;

use AppBundle\Entity\Item;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Item $item
     */
    public function create(Item $item)
    {
        $date = new \DateTime();
        $item->setCreated($date);
        $item->setLastUpdated($date);
        $item->setStatus('selling');

        $this->_em->persist($item);
        $this->_em->flush();
        $this->_em->clear();
    }

    /**
     * @param Item $item
     * @param bool $flush
     */
    public function update(Item $item, $flush = true)
    {

        $date = new \DateTime();
        $item->setLastUpdated($date);

        $this->_em->persist($item);
        if (true == $flush) {
            $this->_em->flush();
            $this->_em->clear();
        }
    }
}
