<?php

namespace AppBundle\Doctrine\Repository;

use AppBundle\Entity\Photo;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Photo $photo
     */
    public function save(Photo $photo)
    {
        $this->_em->persist($photo);
        $this->_em->flush();
        $this->_em->refresh($photo);
    }
}
