<?php

namespace AppBundle\Doctrine\Repository;

use AppBundle\Entity\Rating;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Rating $rating
     */
    public function create(Rating $rating)
    {
        $this->_em->persist($rating);
        $this->_em->flush();
        $this->_em->clear();
    }
}
