parameters:
    directory.import.images: '%kernel.root_dir%/../web/uploads/images'

services:
    validator.unique_user_data:
        class: AppBundle\Service\Validator\Constraints\User\UniqueUserDataValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator }

    user_manager:
        class: AppBundle\Service\User\UserManager
        arguments: ['@doctrine.orm.entity_manager', '@session']
