AppBundle\Entity\User:
    repositoryClass: AppBundle\Doctrine\Repository\UserRepository
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 64
        password:
            type: string
            length: 64
        email:
            type: string
            length: 64
        firstName:
            type: string
            length: 64
        lastName:
            type: string
            length: 64
        address:
            type: string
            length: 128
            nullable: true
        phone:
            type: string
            length: 16
            nullable: true
        city:
            type: string
            length: 32
            nullable: true
        created:
            type: datetime
        lastUpdated:
            type: datetime
        role:
            type: string
            length: 16
    oneToMany:
        comments:
            targetEntity: Comment
            mappedBy: author
