AppBundle\Entity\Item:
    constraints:
        - AppBundle\Service\Validator\Constraints\Item\ValidItemData: ~
    properties:
        name:
            - NotBlank: ~
        basePrice:
            - GreaterThanOrEqual:
                value: 0
                message: 'Pradinė kaina negali būti neigiama'
        buyNowPrice:
            - GreaterThanOrEqual:
                value: 0
                message: 'Pirk dabar kaina negali būti neigiama'
